title: Just the Docs Test for BMS
description: Paul's template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://paulhbartley.github.io/docs_test

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
