title: Documentation Site Test
description: Paul Bartley's template for centralizing all SCS documentation.
theme: just-the-docs

url: https://paulhbartley.github.io/docs_test

# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
